### ISSUE TITLE
大佬，可以做一个 青龙跑的 项目吗？

### ISSUE THREAD

**Issue by tracy1949** [MyFaith/douyu-gift#1]
大佬，可以做一个 青龙跑的 项目吗？

**Comment by MyFaith** [comment]
应该是兼容的，安装好依赖，配置好环境变量就可以

**Comment by tracy1949** [comment]
> 青龙面板跑的日志如下：

斗鱼 荧光棒
## 开始执行... 2023-02-26 18:02:04

2023-02-26 18:02:05.178 | INFO     | __main__:run:13 - ------登录检查开始------
2023-02-26 18:02:05.857 | INFO     | common.login_check:is_login:17 - Cookie有效,登陆成功
2023-02-26 18:02:05.858 | INFO     | __main__:run:15 - ------登录检查结束------
2023-02-26 18:02:05.858 | INFO     | common.dy_glows:get_glow:25 - ------正在获取荧光棒------
Traceback (most recent call last):
  File "/ql/data/scripts/douyu_gift/main.py", line 60, in <module>
    run()
  File "/ql/data/scripts/douyu_gift/main.py", line 18, in run
    get_glow()
  File "/ql/data/scripts/douyu_gift/common/dy_glows.py", line 26, in get_glow
    go_room()
  File "/ql/data/scripts/douyu_gift/common/dy_glows.py", line 96, in go_room
    driver = webdriver.Chrome(executable_path=driver_path, options=chrome_options)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 88, in start
    self._start_process(self.path)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 195, in _start_process
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver'


## 执行结束... 2023-02-26 18:02:06  耗时 2 秒

**Comment by MyFaith** [comment]
这好像并不是我的项目吧

**Comment by MyFaith** [comment]
https://github.com/fletcherjiang/douyu_gift 根据你日志找到的项目地址，可以去那边问问

**Comment by tracy1949** [comment]
> https://github.com/fletcherjiang/douyu_gift 根据你日志找到的项目地址，可以去那边问问
不好意思  弄错了！
请您看一下下面的日志
斗鱼 荧光棒
## 开始执行... 2023-02-26 18:01:09

(node:1092513) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/ql/data/scripts/main.js:1
import puppeteer from "puppeteer";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1


## 执行结束... 2023-02-26 18:01:10  耗时 1 秒

**Comment by tracy1949** [comment]
我已经Docker 跑了斗鱼任务
docker pull starudream/douyu-task
